# src/rag/milvus_utils.py
#
# ─────────────────────────────────────────────────────────────────────────────
# SHARED MILVUS UTILITIES
#
# This module centralises the repeated "create collection if not exists" pattern
# that was previously duplicated in:
#   - src/rag/retriever.py       (knowledge_base collection)
#   - src/routers/rag.py         (knowledge_base collection)
#   - src/memory/vector_memory.py (user_memory collection, twice)
#
# Any file that needs to ensure a Milvus collection exists can call:
#   ensure_collection(client, collection_name)
# ─────────────────────────────────────────────────────────────────────────────

from src.rag.embeddings import EmbeddingClient
# EmbeddingClient.DIMENSIONS (1024) is the vector size used by BGE-M3.
# All collections share the same embedding model, so they all use this dimension.


def ensure_collection(client, collection_name: str) -> None:
    """
    Create a Milvus collection with the standard schema if it does not exist.

    PARAMETERS:
      client          — a MilvusClient instance (already connected)
      collection_name — the name of the collection to create if missing

    SCHEMA:
      id     : INT64        — auto-generated primary key (auto_id=True)
      vector : FLOAT_VECTOR — 1024-dim embedding (BGE-M3 output)
      + any dynamic fields stored via enable_dynamic_field=True
        (e.g. "content", "source", "user_id", "tags", "created_at")

    INDEX:
      COSINE similarity on the "vector" field.
      COSINE measures the angle between vectors (range 0→1).
      It's preferred over L2 for text embeddings because it ignores
      vector magnitude and focuses purely on semantic direction.

    PYTHON CONCEPT — early return / guard clause:
      `if client.has_collection(...)` returns True → nothing to do → return.
      This avoids the indentation of a big `if not ...` block.
      In TypeScript: if (client.hasCollection(...)) return;

    PYTHON CONCEPT — regular (non-async) function:
      MilvusClient.has_collection(), create_schema(), and create_collection()
      are all SYNCHRONOUS — they use a gRPC connection internally, but pymilvus
      exposes them as blocking calls. No `await` needed.
    """
    # Guard: nothing to do if the collection already exists.
    if client.has_collection(collection_name):
        return

    # Deferred import: pymilvus is only required if the collection is missing.
    # If pymilvus is not installed the caller's try/except handles the ImportError.
    from pymilvus import MilvusClient, DataType

    # Build the schema explicitly so auto_id=True is always honoured.
    # pymilvus 2.6.x's shorthand create_collection(dimension=...) silently
    # ignores auto_id, causing "Insert missed a field `id`" errors on insert.
    schema = MilvusClient.create_schema(
        auto_id=True,
        # auto_id=True → Milvus generates a unique INT64 id for every inserted row.
        # Callers never need to supply an "id" field themselves.

        enable_dynamic_field=True,
        # enable_dynamic_field=True → fields not declared in the schema
        # (e.g. "content", "source", "user_id") are stored automatically.
        # This keeps the schema minimal while allowing flexible payloads.
    )

    schema.add_field("id", DataType.INT64, is_primary=True, auto_id=True)
    # Primary key: INT64, auto-generated by Milvus.
    # is_primary=True marks this as the unique row identifier.

    schema.add_field("vector", DataType.FLOAT_VECTOR, dim=EmbeddingClient.DIMENSIONS)
    # The embedding vector field: 1024 floats (BGE-M3 output dimension).
    # This is the field Milvus searches against with ANN (approximate nearest-neighbour).

    # Build the index on the vector field.
    index_params = client.prepare_index_params()
    index_params.add_index(field_name="vector", metric_type="COSINE")
    # metric_type="COSINE" → similarity score ranges 0.0 (unrelated) → 1.0 (identical).
    # Both RAGRetriever (MIN_SCORE 0.72) and VectorMemory (MIN_SCORE 0.78) rely on this.

    client.create_collection(
        collection_name=collection_name,
        schema=schema,
        index_params=index_params,
    )

